/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/magazzino`; params?: Router.UnknownInputParams; } | { pathname: `/nuovo-appuntamento`; params?: Router.UnknownInputParams; } | { pathname: `/nuovo-cliente`; params?: Router.UnknownInputParams; } | { pathname: `/obd`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/altro` | `/altro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clienti` | `/clienti`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/appointment/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/magazzino`; params?: Router.UnknownOutputParams; } | { pathname: `/nuovo-appuntamento`; params?: Router.UnknownOutputParams; } | { pathname: `/nuovo-cliente`; params?: Router.UnknownOutputParams; } | { pathname: `/obd`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/altro` | `/altro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clienti` | `/clienti`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/appointment/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/analytics${`?${string}` | `#${string}` | ''}` | `/magazzino${`?${string}` | `#${string}` | ''}` | `/nuovo-appuntamento${`?${string}` | `#${string}` | ''}` | `/nuovo-cliente${`?${string}` | `#${string}` | ''}` | `/obd${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/altro${`?${string}` | `#${string}` | ''}` | `/altro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendario${`?${string}` | `#${string}` | ''}` | `/calendario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clienti${`?${string}` | `#${string}` | ''}` | `/clienti${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/magazzino`; params?: Router.UnknownInputParams; } | { pathname: `/nuovo-appuntamento`; params?: Router.UnknownInputParams; } | { pathname: `/nuovo-cliente`; params?: Router.UnknownInputParams; } | { pathname: `/obd`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/altro` | `/altro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clienti` | `/clienti`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/appointment/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/appointment/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
